apiVersion: v1
kind: Namespace
metadata:
  name: flowstate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowstatesrv
  namespace: flowstate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flowstatesrv
  template:
    metadata:
      labels:
        app: flowstatesrv
    spec:
      containers:
        - name: flowstatesrv
          image: registry2.makasim.com/flowstatesrv:${VERSION}
          ports:
            - containerPort: 8282
          env:
            - name: FLOWSTATESRV_ADDR
              value: "0.0.0.0:9282"
            - name: CORS_ENABLED
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: flowstatesrv-service
  namespace: flowstate
spec:
  selector:
    app: flowstatesrv
  ports:
    - protocol: TCP
      port: 9282
      targetPort: 9282
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flowstatesrv-ingress
  namespace: flowstate
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: http,https
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  rules:
    - host: flowstate.makasim.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  flowstatesrv-service
                port:
                  number: 9282