version: '3'

tasks:
  genproto:
    cmds:
      - buf lint
      - rm -rf protogen/*
      - buf generate

  build:
    cmds:
      - |
        cd ui
        pnpm i
        pnpm build

      - |
        go mod tidy && go mod vendor
        GOOS=linux GOARCH=arm64 go build -o flowstatesrv ./main/
        
        VERSION="$(git rev-list -1 HEAD | cut -c1-8)"
        if [ -n "$(git diff)" ]; then
          VERSION="${VERSION}-$(git diff | sha1sum | awk '{print $1}' | cut -c1-8)"
        fi
        if [ -n "$(git diff --cached)" ]; then
          VERSION="${VERSION}-$(git diff --cached | sha1sum | awk '{print $1}' | cut -c1-8)"
        fi
        echo "Building flowstatesrv:$VERSION"
        docker build --platform="linux/arm64" -t "flowstatesrv:$VERSION" .

  push:
    cmds:
      - |
        VERSION="$(git rev-list -1 HEAD | cut -c1-8)"
        if [ -n "$(git diff)" ]; then
          VERSION="${VERSION}-$(git diff | sha1sum | awk '{print $1}' | cut -c1-8)"
        fi
        if [ -n "$(git diff --cached)" ]; then
          VERSION="${VERSION}-$(git diff --cached | sha1sum | awk '{print $1}' | cut -c1-8)"
        fi
        
        docker tag "flowstatesrv:$VERSION" "registry2.makasim.com/flowstatesrv:$VERSION"
        echo "Pushing registry2.makasim.com/flowstatesrv:$VERSION"
        docker push "registry2.makasim.com/flowstatesrv:$VERSION"
