// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: flowstate/v1alpha1/commands.proto

package flowstatev1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateRef *StateRef `protobuf:"bytes,1,opt,name=state_ref,json=stateRef,proto3" json:"state_ref,omitempty"`
	FlowId   string    `protobuf:"bytes,2,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
}

func (x *Transit) Reset() {
	*x = Transit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transit) ProtoMessage() {}

func (x *Transit) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transit.ProtoReflect.Descriptor instead.
func (*Transit) Descriptor() ([]byte, []int) {
	return file_flowstate_v1alpha1_commands_proto_rawDescGZIP(), []int{0}
}

func (x *Transit) GetStateRef() *StateRef {
	if x != nil {
		return x.StateRef
	}
	return nil
}

func (x *Transit) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

type TransitResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateRef *StateRef `protobuf:"bytes,1,opt,name=state_ref,json=stateRef,proto3" json:"state_ref,omitempty"`
}

func (x *TransitResult) Reset() {
	*x = TransitResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransitResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitResult) ProtoMessage() {}

func (x *TransitResult) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitResult.ProtoReflect.Descriptor instead.
func (*TransitResult) Descriptor() ([]byte, []int) {
	return file_flowstate_v1alpha1_commands_proto_rawDescGZIP(), []int{1}
}

func (x *TransitResult) GetStateRef() *StateRef {
	if x != nil {
		return x.StateRef
	}
	return nil
}

type Pause struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateRef *StateRef `protobuf:"bytes,1,opt,name=state_ref,json=stateRef,proto3" json:"state_ref,omitempty"`
	FlowId   string    `protobuf:"bytes,2,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
}

func (x *Pause) Reset() {
	*x = Pause{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pause) ProtoMessage() {}

func (x *Pause) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pause.ProtoReflect.Descriptor instead.
func (*Pause) Descriptor() ([]byte, []int) {
	return file_flowstate_v1alpha1_commands_proto_rawDescGZIP(), []int{2}
}

func (x *Pause) GetStateRef() *StateRef {
	if x != nil {
		return x.StateRef
	}
	return nil
}

func (x *Pause) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

type PauseResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateRef *StateRef `protobuf:"bytes,1,opt,name=state_ref,json=stateRef,proto3" json:"state_ref,omitempty"`
}

func (x *PauseResult) Reset() {
	*x = PauseResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PauseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseResult) ProtoMessage() {}

func (x *PauseResult) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseResult.ProtoReflect.Descriptor instead.
func (*PauseResult) Descriptor() ([]byte, []int) {
	return file_flowstate_v1alpha1_commands_proto_rawDescGZIP(), []int{3}
}

func (x *PauseResult) GetStateRef() *StateRef {
	if x != nil {
		return x.StateRef
	}
	return nil
}

type Resume struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateRef *StateRef `protobuf:"bytes,1,opt,name=state_ref,json=stateRef,proto3" json:"state_ref,omitempty"`
}

func (x *Resume) Reset() {
	*x = Resume{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resume) ProtoMessage() {}

func (x *Resume) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resume.ProtoReflect.Descriptor instead.
func (*Resume) Descriptor() ([]byte, []int) {
	return file_flowstate_v1alpha1_commands_proto_rawDescGZIP(), []int{4}
}

func (x *Resume) GetStateRef() *StateRef {
	if x != nil {
		return x.StateRef
	}
	return nil
}

type ResumeResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateRef *StateRef `protobuf:"bytes,1,opt,name=state_ref,json=stateRef,proto3" json:"state_ref,omitempty"`
}

func (x *ResumeResult) Reset() {
	*x = ResumeResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResumeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeResult) ProtoMessage() {}

func (x *ResumeResult) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeResult.ProtoReflect.Descriptor instead.
func (*ResumeResult) Descriptor() ([]byte, []int) {
	return file_flowstate_v1alpha1_commands_proto_rawDescGZIP(), []int{5}
}

func (x *ResumeResult) GetStateRef() *StateRef {
	if x != nil {
		return x.StateRef
	}
	return nil
}

type End struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateRef *StateRef `protobuf:"bytes,1,opt,name=state_ref,json=stateRef,proto3" json:"state_ref,omitempty"`
}

func (x *End) Reset() {
	*x = End{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *End) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*End) ProtoMessage() {}

func (x *End) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use End.ProtoReflect.Descriptor instead.
func (*End) Descriptor() ([]byte, []int) {
	return file_flowstate_v1alpha1_commands_proto_rawDescGZIP(), []int{6}
}

func (x *End) GetStateRef() *StateRef {
	if x != nil {
		return x.StateRef
	}
	return nil
}

type EndResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateRef *StateRef `protobuf:"bytes,1,opt,name=state_ref,json=stateRef,proto3" json:"state_ref,omitempty"`
}

func (x *EndResult) Reset() {
	*x = EndResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndResult) ProtoMessage() {}

func (x *EndResult) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndResult.ProtoReflect.Descriptor instead.
func (*EndResult) Descriptor() ([]byte, []int) {
	return file_flowstate_v1alpha1_commands_proto_rawDescGZIP(), []int{7}
}

func (x *EndResult) GetStateRef() *StateRef {
	if x != nil {
		return x.StateRef
	}
	return nil
}

type Execute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateRef *StateRef `protobuf:"bytes,1,opt,name=state_ref,json=stateRef,proto3" json:"state_ref,omitempty"`
}

func (x *Execute) Reset() {
	*x = Execute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Execute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Execute) ProtoMessage() {}

func (x *Execute) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Execute.ProtoReflect.Descriptor instead.
func (*Execute) Descriptor() ([]byte, []int) {
	return file_flowstate_v1alpha1_commands_proto_rawDescGZIP(), []int{8}
}

func (x *Execute) GetStateRef() *StateRef {
	if x != nil {
		return x.StateRef
	}
	return nil
}

type ExecuteResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateRef *StateRef `protobuf:"bytes,1,opt,name=state_ref,json=stateRef,proto3" json:"state_ref,omitempty"`
}

func (x *ExecuteResult) Reset() {
	*x = ExecuteResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResult) ProtoMessage() {}

func (x *ExecuteResult) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResult.ProtoReflect.Descriptor instead.
func (*ExecuteResult) Descriptor() ([]byte, []int) {
	return file_flowstate_v1alpha1_commands_proto_rawDescGZIP(), []int{9}
}

func (x *ExecuteResult) GetStateRef() *StateRef {
	if x != nil {
		return x.StateRef
	}
	return nil
}

type Delay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateRef *StateRef `protobuf:"bytes,1,opt,name=state_ref,json=stateRef,proto3" json:"state_ref,omitempty"`
	Duration string    `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Commit   bool      `protobuf:"varint,3,opt,name=commit,proto3" json:"commit,omitempty"`
}

func (x *Delay) Reset() {
	*x = Delay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Delay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delay) ProtoMessage() {}

func (x *Delay) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delay.ProtoReflect.Descriptor instead.
func (*Delay) Descriptor() ([]byte, []int) {
	return file_flowstate_v1alpha1_commands_proto_rawDescGZIP(), []int{10}
}

func (x *Delay) GetStateRef() *StateRef {
	if x != nil {
		return x.StateRef
	}
	return nil
}

func (x *Delay) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *Delay) GetCommit() bool {
	if x != nil {
		return x.Commit
	}
	return false
}

type DelayResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateRef *StateRef `protobuf:"bytes,1,opt,name=state_ref,json=stateRef,proto3" json:"state_ref,omitempty"`
	Duration string    `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Commit   bool      `protobuf:"varint,3,opt,name=commit,proto3" json:"commit,omitempty"`
}

func (x *DelayResult) Reset() {
	*x = DelayResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelayResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelayResult) ProtoMessage() {}

func (x *DelayResult) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelayResult.ProtoReflect.Descriptor instead.
func (*DelayResult) Descriptor() ([]byte, []int) {
	return file_flowstate_v1alpha1_commands_proto_rawDescGZIP(), []int{11}
}

func (x *DelayResult) GetStateRef() *StateRef {
	if x != nil {
		return x.StateRef
	}
	return nil
}

func (x *DelayResult) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *DelayResult) GetCommit() bool {
	if x != nil {
		return x.Commit
	}
	return false
}

type Commit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commands []*anypb.Any `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
}

func (x *Commit) Reset() {
	*x = Commit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commit) ProtoMessage() {}

func (x *Commit) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commit.ProtoReflect.Descriptor instead.
func (*Commit) Descriptor() ([]byte, []int) {
	return file_flowstate_v1alpha1_commands_proto_rawDescGZIP(), []int{12}
}

func (x *Commit) GetCommands() []*anypb.Any {
	if x != nil {
		return x.Commands
	}
	return nil
}

type CommitResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*anypb.Any `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *CommitResult) Reset() {
	*x = CommitResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResult) ProtoMessage() {}

func (x *CommitResult) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResult.ProtoReflect.Descriptor instead.
func (*CommitResult) Descriptor() ([]byte, []int) {
	return file_flowstate_v1alpha1_commands_proto_rawDescGZIP(), []int{13}
}

func (x *CommitResult) GetResults() []*anypb.Any {
	if x != nil {
		return x.Results
	}
	return nil
}

type Noop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateRef *StateRef `protobuf:"bytes,1,opt,name=state_ref,json=stateRef,proto3" json:"state_ref,omitempty"`
}

func (x *Noop) Reset() {
	*x = Noop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Noop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Noop) ProtoMessage() {}

func (x *Noop) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Noop.ProtoReflect.Descriptor instead.
func (*Noop) Descriptor() ([]byte, []int) {
	return file_flowstate_v1alpha1_commands_proto_rawDescGZIP(), []int{14}
}

func (x *Noop) GetStateRef() *StateRef {
	if x != nil {
		return x.StateRef
	}
	return nil
}

type NoopResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateRef *StateRef `protobuf:"bytes,1,opt,name=state_ref,json=stateRef,proto3" json:"state_ref,omitempty"`
}

func (x *NoopResult) Reset() {
	*x = NoopResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoopResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoopResult) ProtoMessage() {}

func (x *NoopResult) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoopResult.ProtoReflect.Descriptor instead.
func (*NoopResult) Descriptor() ([]byte, []int) {
	return file_flowstate_v1alpha1_commands_proto_rawDescGZIP(), []int{15}
}

func (x *NoopResult) GetStateRef() *StateRef {
	if x != nil {
		return x.StateRef
	}
	return nil
}

type Serialize struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SerializableStateRef *StateRef `protobuf:"bytes,1,opt,name=serializable_state_ref,json=serializableStateRef,proto3" json:"serializable_state_ref,omitempty"`
	StateRef             *StateRef `protobuf:"bytes,2,opt,name=state_ref,json=stateRef,proto3" json:"state_ref,omitempty"`
	Annotation           string    `protobuf:"bytes,3,opt,name=annotation,proto3" json:"annotation,omitempty"`
}

func (x *Serialize) Reset() {
	*x = Serialize{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Serialize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Serialize) ProtoMessage() {}

func (x *Serialize) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Serialize.ProtoReflect.Descriptor instead.
func (*Serialize) Descriptor() ([]byte, []int) {
	return file_flowstate_v1alpha1_commands_proto_rawDescGZIP(), []int{16}
}

func (x *Serialize) GetSerializableStateRef() *StateRef {
	if x != nil {
		return x.SerializableStateRef
	}
	return nil
}

func (x *Serialize) GetStateRef() *StateRef {
	if x != nil {
		return x.StateRef
	}
	return nil
}

func (x *Serialize) GetAnnotation() string {
	if x != nil {
		return x.Annotation
	}
	return ""
}

type SerializeResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SerializableStateRef *StateRef `protobuf:"bytes,1,opt,name=serializable_state_ref,json=serializableStateRef,proto3" json:"serializable_state_ref,omitempty"`
	StateRef             *StateRef `protobuf:"bytes,2,opt,name=state_ref,json=stateRef,proto3" json:"state_ref,omitempty"`
	Annotation           string    `protobuf:"bytes,3,opt,name=annotation,proto3" json:"annotation,omitempty"`
}

func (x *SerializeResult) Reset() {
	*x = SerializeResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SerializeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializeResult) ProtoMessage() {}

func (x *SerializeResult) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializeResult.ProtoReflect.Descriptor instead.
func (*SerializeResult) Descriptor() ([]byte, []int) {
	return file_flowstate_v1alpha1_commands_proto_rawDescGZIP(), []int{17}
}

func (x *SerializeResult) GetSerializableStateRef() *StateRef {
	if x != nil {
		return x.SerializableStateRef
	}
	return nil
}

func (x *SerializeResult) GetStateRef() *StateRef {
	if x != nil {
		return x.StateRef
	}
	return nil
}

func (x *SerializeResult) GetAnnotation() string {
	if x != nil {
		return x.Annotation
	}
	return ""
}

type Deserialize struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeserializedStateRef *StateRef `protobuf:"bytes,1,opt,name=deserialized_state_ref,json=deserializedStateRef,proto3" json:"deserialized_state_ref,omitempty"`
	StateRef             *StateRef `protobuf:"bytes,2,opt,name=state_ref,json=stateRef,proto3" json:"state_ref,omitempty"`
	Annotation           string    `protobuf:"bytes,3,opt,name=annotation,proto3" json:"annotation,omitempty"`
}

func (x *Deserialize) Reset() {
	*x = Deserialize{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Deserialize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deserialize) ProtoMessage() {}

func (x *Deserialize) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deserialize.ProtoReflect.Descriptor instead.
func (*Deserialize) Descriptor() ([]byte, []int) {
	return file_flowstate_v1alpha1_commands_proto_rawDescGZIP(), []int{18}
}

func (x *Deserialize) GetDeserializedStateRef() *StateRef {
	if x != nil {
		return x.DeserializedStateRef
	}
	return nil
}

func (x *Deserialize) GetStateRef() *StateRef {
	if x != nil {
		return x.StateRef
	}
	return nil
}

func (x *Deserialize) GetAnnotation() string {
	if x != nil {
		return x.Annotation
	}
	return ""
}

type DeserializeResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeserializedStateRef *StateRef `protobuf:"bytes,1,opt,name=deserialized_state_ref,json=deserializedStateRef,proto3" json:"deserialized_state_ref,omitempty"`
	StateRef             *StateRef `protobuf:"bytes,2,opt,name=state_ref,json=stateRef,proto3" json:"state_ref,omitempty"`
	Annotation           string    `protobuf:"bytes,3,opt,name=annotation,proto3" json:"annotation,omitempty"`
}

func (x *DeserializeResult) Reset() {
	*x = DeserializeResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeserializeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeserializeResult) ProtoMessage() {}

func (x *DeserializeResult) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1alpha1_commands_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeserializeResult.ProtoReflect.Descriptor instead.
func (*DeserializeResult) Descriptor() ([]byte, []int) {
	return file_flowstate_v1alpha1_commands_proto_rawDescGZIP(), []int{19}
}

func (x *DeserializeResult) GetDeserializedStateRef() *StateRef {
	if x != nil {
		return x.DeserializedStateRef
	}
	return nil
}

func (x *DeserializeResult) GetStateRef() *StateRef {
	if x != nil {
		return x.StateRef
	}
	return nil
}

func (x *DeserializeResult) GetAnnotation() string {
	if x != nil {
		return x.Annotation
	}
	return ""
}

var File_flowstate_v1alpha1_commands_proto protoreflect.FileDescriptor

var file_flowstate_v1alpha1_commands_proto_rawDesc = []byte{
	0x0a, 0x21, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x12, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x1a, 0x1e, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x5d, 0x0a, 0x07, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x12, 0x39, 0x0a,
	0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x66, 0x52, 0x08,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x66, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x6c, 0x6f, 0x77,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6c, 0x6f, 0x77, 0x49,
	0x64, 0x22, 0x4a, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x39, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x66, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x66, 0x22, 0x5b, 0x0a,
	0x05, 0x50, 0x61, 0x75, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f,
	0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x66, 0x6c, 0x6f, 0x77,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x66, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x66, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x66, 0x6c, 0x6f, 0x77, 0x49, 0x64, 0x22, 0x48, 0x0a, 0x0b, 0x50, 0x61,
	0x75, 0x73, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x39, 0x0a, 0x09, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x66,
	0x6c, 0x6f, 0x77, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x66, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x66, 0x22, 0x43, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x12, 0x39,
	0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x66, 0x52,
	0x08, 0x73, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x66, 0x22, 0x49, 0x0a, 0x0c, 0x52, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x39, 0x0a, 0x09, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x66,
	0x6c, 0x6f, 0x77, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x66, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x66, 0x22, 0x40, 0x0a, 0x03, 0x45, 0x6e, 0x64, 0x12, 0x39, 0x0a, 0x09, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x66, 0x52, 0x08, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x66, 0x22, 0x46, 0x0a, 0x09, 0x45, 0x6e, 0x64, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x39, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x66,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x66, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x66, 0x22, 0x44,
	0x0a, 0x07, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x12, 0x39, 0x0a, 0x09, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x66,
	0x6c, 0x6f, 0x77, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x66, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x66, 0x22, 0x4a, 0x0a, 0x0d, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x39, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x72,
	0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x66, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x66,
	0x22, 0x76, 0x0a, 0x05, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x12, 0x39, 0x0a, 0x09, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x66,
	0x6c, 0x6f, 0x77, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x66, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x66, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x22, 0x7c, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x61,
	0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x39, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x5f, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x66, 0x6c, 0x6f,
	0x77, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x66, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x66, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x22, 0x3a, 0x0a, 0x06, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x12, 0x30, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x73, 0x22, 0x3e, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x2e, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x22, 0x41, 0x0a, 0x04, 0x4e, 0x6f, 0x6f, 0x70, 0x12, 0x39, 0x0a, 0x09, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x66, 0x6c, 0x6f, 0x77, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x66, 0x52, 0x08, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x66, 0x22, 0x47, 0x0a, 0x0a, 0x4e, 0x6f, 0x6f, 0x70, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x39, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x66,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x66, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x66, 0x22, 0xba,
	0x01, 0x0a, 0x09, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x12, 0x52, 0x0a, 0x16,
	0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x66,
	0x6c, 0x6f, 0x77, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x66, 0x52, 0x14, 0x73, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x69, 0x7a, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x66,
	0x12, 0x39, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x66, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x66, 0x12, 0x1e, 0x0a, 0x0a, 0x61,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xc0, 0x01, 0x0a, 0x0f,
	0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x52, 0x0a, 0x16, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x62, 0x6c, 0x65, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x66, 0x52, 0x14, 0x73,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x66, 0x12, 0x39, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x66,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x66, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x66, 0x12, 0x1e,
	0x0a, 0x0a, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xbc,
	0x01, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x12, 0x52,
	0x0a, 0x16, 0x64, 0x65, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x66, 0x52, 0x14, 0x64, 0x65,
	0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x66, 0x12, 0x39, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x66, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x66, 0x12, 0x1e, 0x0a,
	0x0a, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xc2, 0x01,
	0x0a, 0x11, 0x44, 0x65, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x52, 0x0a, 0x16, 0x64, 0x65, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69,
	0x7a, 0x65, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x66, 0x52, 0x14, 0x64, 0x65, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x66, 0x12, 0x39, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x5f, 0x72, 0x65, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x66, 0x6c, 0x6f,
	0x77, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x66, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x66, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x42, 0xdf, 0x01, 0x0a, 0x16, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x42, 0x0d, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x4d,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x6b, 0x61, 0x73,
	0x69, 0x6d, 0x2f, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x72, 0x76, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x3b, 0x66, 0x6c, 0x6f, 0x77,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0xa2, 0x02, 0x03,
	0x46, 0x58, 0x58, 0xaa, 0x02, 0x12, 0x46, 0x6c, 0x6f, 0x77, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e,
	0x56, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0xca, 0x02, 0x12, 0x46, 0x6c, 0x6f, 0x77, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x5c, 0x56, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0xe2, 0x02, 0x1e,
	0x46, 0x6c, 0x6f, 0x77, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5c, 0x56, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02,
	0x13, 0x46, 0x6c, 0x6f, 0x77, 0x73, 0x74, 0x61, 0x74, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_flowstate_v1alpha1_commands_proto_rawDescOnce sync.Once
	file_flowstate_v1alpha1_commands_proto_rawDescData = file_flowstate_v1alpha1_commands_proto_rawDesc
)

func file_flowstate_v1alpha1_commands_proto_rawDescGZIP() []byte {
	file_flowstate_v1alpha1_commands_proto_rawDescOnce.Do(func() {
		file_flowstate_v1alpha1_commands_proto_rawDescData = protoimpl.X.CompressGZIP(file_flowstate_v1alpha1_commands_proto_rawDescData)
	})
	return file_flowstate_v1alpha1_commands_proto_rawDescData
}

var file_flowstate_v1alpha1_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_flowstate_v1alpha1_commands_proto_goTypes = []interface{}{
	(*Transit)(nil),           // 0: flowstate.v1alpha1.Transit
	(*TransitResult)(nil),     // 1: flowstate.v1alpha1.TransitResult
	(*Pause)(nil),             // 2: flowstate.v1alpha1.Pause
	(*PauseResult)(nil),       // 3: flowstate.v1alpha1.PauseResult
	(*Resume)(nil),            // 4: flowstate.v1alpha1.Resume
	(*ResumeResult)(nil),      // 5: flowstate.v1alpha1.ResumeResult
	(*End)(nil),               // 6: flowstate.v1alpha1.End
	(*EndResult)(nil),         // 7: flowstate.v1alpha1.EndResult
	(*Execute)(nil),           // 8: flowstate.v1alpha1.Execute
	(*ExecuteResult)(nil),     // 9: flowstate.v1alpha1.ExecuteResult
	(*Delay)(nil),             // 10: flowstate.v1alpha1.Delay
	(*DelayResult)(nil),       // 11: flowstate.v1alpha1.DelayResult
	(*Commit)(nil),            // 12: flowstate.v1alpha1.Commit
	(*CommitResult)(nil),      // 13: flowstate.v1alpha1.CommitResult
	(*Noop)(nil),              // 14: flowstate.v1alpha1.Noop
	(*NoopResult)(nil),        // 15: flowstate.v1alpha1.NoopResult
	(*Serialize)(nil),         // 16: flowstate.v1alpha1.Serialize
	(*SerializeResult)(nil),   // 17: flowstate.v1alpha1.SerializeResult
	(*Deserialize)(nil),       // 18: flowstate.v1alpha1.Deserialize
	(*DeserializeResult)(nil), // 19: flowstate.v1alpha1.DeserializeResult
	(*StateRef)(nil),          // 20: flowstate.v1alpha1.StateRef
	(*anypb.Any)(nil),         // 21: google.protobuf.Any
}
var file_flowstate_v1alpha1_commands_proto_depIdxs = []int32{
	20, // 0: flowstate.v1alpha1.Transit.state_ref:type_name -> flowstate.v1alpha1.StateRef
	20, // 1: flowstate.v1alpha1.TransitResult.state_ref:type_name -> flowstate.v1alpha1.StateRef
	20, // 2: flowstate.v1alpha1.Pause.state_ref:type_name -> flowstate.v1alpha1.StateRef
	20, // 3: flowstate.v1alpha1.PauseResult.state_ref:type_name -> flowstate.v1alpha1.StateRef
	20, // 4: flowstate.v1alpha1.Resume.state_ref:type_name -> flowstate.v1alpha1.StateRef
	20, // 5: flowstate.v1alpha1.ResumeResult.state_ref:type_name -> flowstate.v1alpha1.StateRef
	20, // 6: flowstate.v1alpha1.End.state_ref:type_name -> flowstate.v1alpha1.StateRef
	20, // 7: flowstate.v1alpha1.EndResult.state_ref:type_name -> flowstate.v1alpha1.StateRef
	20, // 8: flowstate.v1alpha1.Execute.state_ref:type_name -> flowstate.v1alpha1.StateRef
	20, // 9: flowstate.v1alpha1.ExecuteResult.state_ref:type_name -> flowstate.v1alpha1.StateRef
	20, // 10: flowstate.v1alpha1.Delay.state_ref:type_name -> flowstate.v1alpha1.StateRef
	20, // 11: flowstate.v1alpha1.DelayResult.state_ref:type_name -> flowstate.v1alpha1.StateRef
	21, // 12: flowstate.v1alpha1.Commit.commands:type_name -> google.protobuf.Any
	21, // 13: flowstate.v1alpha1.CommitResult.results:type_name -> google.protobuf.Any
	20, // 14: flowstate.v1alpha1.Noop.state_ref:type_name -> flowstate.v1alpha1.StateRef
	20, // 15: flowstate.v1alpha1.NoopResult.state_ref:type_name -> flowstate.v1alpha1.StateRef
	20, // 16: flowstate.v1alpha1.Serialize.serializable_state_ref:type_name -> flowstate.v1alpha1.StateRef
	20, // 17: flowstate.v1alpha1.Serialize.state_ref:type_name -> flowstate.v1alpha1.StateRef
	20, // 18: flowstate.v1alpha1.SerializeResult.serializable_state_ref:type_name -> flowstate.v1alpha1.StateRef
	20, // 19: flowstate.v1alpha1.SerializeResult.state_ref:type_name -> flowstate.v1alpha1.StateRef
	20, // 20: flowstate.v1alpha1.Deserialize.deserialized_state_ref:type_name -> flowstate.v1alpha1.StateRef
	20, // 21: flowstate.v1alpha1.Deserialize.state_ref:type_name -> flowstate.v1alpha1.StateRef
	20, // 22: flowstate.v1alpha1.DeserializeResult.deserialized_state_ref:type_name -> flowstate.v1alpha1.StateRef
	20, // 23: flowstate.v1alpha1.DeserializeResult.state_ref:type_name -> flowstate.v1alpha1.StateRef
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_flowstate_v1alpha1_commands_proto_init() }
func file_flowstate_v1alpha1_commands_proto_init() {
	if File_flowstate_v1alpha1_commands_proto != nil {
		return
	}
	file_flowstate_v1alpha1_state_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_flowstate_v1alpha1_commands_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flowstate_v1alpha1_commands_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransitResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flowstate_v1alpha1_commands_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pause); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flowstate_v1alpha1_commands_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PauseResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flowstate_v1alpha1_commands_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resume); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flowstate_v1alpha1_commands_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResumeResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flowstate_v1alpha1_commands_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*End); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flowstate_v1alpha1_commands_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flowstate_v1alpha1_commands_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Execute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flowstate_v1alpha1_commands_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flowstate_v1alpha1_commands_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Delay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flowstate_v1alpha1_commands_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelayResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flowstate_v1alpha1_commands_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Commit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flowstate_v1alpha1_commands_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flowstate_v1alpha1_commands_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Noop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flowstate_v1alpha1_commands_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoopResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flowstate_v1alpha1_commands_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Serialize); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flowstate_v1alpha1_commands_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SerializeResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flowstate_v1alpha1_commands_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Deserialize); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flowstate_v1alpha1_commands_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeserializeResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_flowstate_v1alpha1_commands_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flowstate_v1alpha1_commands_proto_goTypes,
		DependencyIndexes: file_flowstate_v1alpha1_commands_proto_depIdxs,
		MessageInfos:      file_flowstate_v1alpha1_commands_proto_msgTypes,
	}.Build()
	File_flowstate_v1alpha1_commands_proto = out.File
	file_flowstate_v1alpha1_commands_proto_rawDesc = nil
	file_flowstate_v1alpha1_commands_proto_goTypes = nil
	file_flowstate_v1alpha1_commands_proto_depIdxs = nil
}
