// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: flowstate/client/v1/client.proto

package clientv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/makasim/flowstatesrv/protogen/flowstate/client/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ClientServiceName is the fully-qualified name of the ClientService service.
	ClientServiceName = "flowstate.client.v1.ClientService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ClientServiceExecuteProcedure is the fully-qualified name of the ClientService's Execute RPC.
	ClientServiceExecuteProcedure = "/flowstate.client.v1.ClientService/Execute"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	clientServiceServiceDescriptor       = v1.File_flowstate_client_v1_client_proto.Services().ByName("ClientService")
	clientServiceExecuteMethodDescriptor = clientServiceServiceDescriptor.Methods().ByName("Execute")
)

// ClientServiceClient is a client for the flowstate.client.v1.ClientService service.
type ClientServiceClient interface {
	Execute(context.Context, *connect.Request[v1.ExecuteRequest]) (*connect.Response[v1.ExecuteResponse], error)
}

// NewClientServiceClient constructs a client for the flowstate.client.v1.ClientService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewClientServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ClientServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &clientServiceClient{
		execute: connect.NewClient[v1.ExecuteRequest, v1.ExecuteResponse](
			httpClient,
			baseURL+ClientServiceExecuteProcedure,
			connect.WithSchema(clientServiceExecuteMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// clientServiceClient implements ClientServiceClient.
type clientServiceClient struct {
	execute *connect.Client[v1.ExecuteRequest, v1.ExecuteResponse]
}

// Execute calls flowstate.client.v1.ClientService.Execute.
func (c *clientServiceClient) Execute(ctx context.Context, req *connect.Request[v1.ExecuteRequest]) (*connect.Response[v1.ExecuteResponse], error) {
	return c.execute.CallUnary(ctx, req)
}

// ClientServiceHandler is an implementation of the flowstate.client.v1.ClientService service.
type ClientServiceHandler interface {
	Execute(context.Context, *connect.Request[v1.ExecuteRequest]) (*connect.Response[v1.ExecuteResponse], error)
}

// NewClientServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewClientServiceHandler(svc ClientServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	clientServiceExecuteHandler := connect.NewUnaryHandler(
		ClientServiceExecuteProcedure,
		svc.Execute,
		connect.WithSchema(clientServiceExecuteMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/flowstate.client.v1.ClientService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ClientServiceExecuteProcedure:
			clientServiceExecuteHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedClientServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedClientServiceHandler struct{}

func (UnimplementedClientServiceHandler) Execute(context.Context, *connect.Request[v1.ExecuteRequest]) (*connect.Response[v1.ExecuteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("flowstate.client.v1.ClientService.Execute is not implemented"))
}
